// src/config/blog-seo.ts
// Blog tags from Semrush AU Informational keywords (label Informational, alone or with Commercial). Volumes are in docs/seo-keyword-allocation.md.
// Navigational keywords are answered in the FAQ, not here. Posts about batteries, tuning and maintenance have few specific tags
// because the Semrush export contains almost no informational demand for those topics.
export const BLOG_TAGS: Record<string, string[]> = {
  "sur-ron-vs-talaria-australia-buyers-guide": ["electric bikes australia","how much are electric bikes","cheap electric dirt bikes","electric dirt bike","electric dirt bike australia","electric dirt bikes","electric bike australia"],
  "how-to-charge-maintain-electric-dirt-bike-batteries": ["electric bikes australia","electric bike australia","electric dirt bike","electric dirt bike australia","electric dirt bikes"],
  "stark-varg-motocross-revolution-australia": ["electric bike australia","electric dirt bike","electric dirt bike australia","electric dirt bikes"],
  "are-electric-dirt-bikes-legal-in-australia": ["electric bikes australia","electric bike laws australia","electric bike laws qld","electric bike regulations nsw","nsw e bike certification laws","electric dirt bikes","electric bike australia","electric dirt bike"],
  "top-10-best-electric-dirt-bikes-australia-2026": ["electric bikes australia","how much are electric bikes","cheap electric dirt bikes","electric bike australia","electric dirt bike","electric dirt bike australia","electric dirt bikes"],
  "72v-vs-60v-electric-dirt-bike-battery-upgrade-guide": ["electric bikes australia","electric dirt bike","electric dirt bike australia","electric dirt bikes","electric bike australia"],
  "talaria-dragon-komodo-full-size-electric-enduro-review": ["electric bikes australia","electric bike australia","electric dirt bike","electric dirt bike australia","electric dirt bikes"],
  "torp-tc500-vs-bac4000-controller-comparison": ["electric bikes australia","electric dirt bike","electric dirt bike australia","electric dirt bikes","electric bike australia"],
  "electric-dirt-bike-fast-chargers-and-solar-generators": ["electric bikes australia","fast electric bikes","fastest ebike australia","fastest e bike australia","faster electric bike","electric bike australia","electric dirt bike","electric dirt bike australia"],
  "suspension-upgrades-for-sur-ron-and-talaria": ["electric bikes australia","electric bike australia","electric dirt bike","electric dirt bike australia","electric dirt bikes"],
  "electric-dirt-bike-vs-petrol-motocross-running-costs": ["electric bikes australia","electric bike australia","electric dirt bike","electric dirt bike australia","electric dirt bikes"],
  "best-electric-dirt-bikes-for-beginners-and-teens": ["electric bikes australia","childrens electric bikes","small electric bike","ktm electric dirt bike","electric dirt bike australia","electric dirt bikes","electric bike australia","electric dirt bike"],
  "electric-dirt-bike-braking-upgrades-250mm-rotors": ["electric bikes australia","electric dirt bike","electric dirt bike australia","electric dirt bikes","electric bike australia"],
  "supermoto-wheel-conversion-for-electric-dirt-bikes": ["electric bikes australia","electric dirt bike","electric dirt bike australia","electric dirt bikes","electric bike australia"],
  "complete-pre-ride-and-post-wash-maintenance-guide": ["electric dirt bike","electric dirt bike australia","electric dirt bikes","electric bike australia"],
  "molicel-p45b-vs-samsung-50s-lithium-cells": ["australian e bikes","australian e-bike","electric dirt bikes","electric bike australia","electric dirt bike","electric dirt bike australia"],
  "how-to-transport-electric-dirt-bikes-car-hitch-racks": ["electric bikes australia","electric dirt bike","electric dirt bike australia","electric dirt bikes","electric bike australia"],
  "essential-aftermarket-mods-for-surron-light-bee-x": ["electric dirt bikes","electric bike australia","electric dirt bike","electric dirt bike australia"],
  "extending-single-charge-range-on-rugged-bush-trails": ["electric bikes australia","electric dirt bike","electric dirt bike australia","electric dirt bikes","electric bike australia"],
  "future-of-electric-motocross-racing-in-australia": ["electric bikes australia","electric dirt bike australia","electric dirt bikes","electric bike australia","electric dirt bike"],
  "what-is-an-electric-dirt-bike-complete-guide-australia": ["electric bikes australia","electric bike australia","electric dirt bike","electric dirt bike australia","electric dirt bikes"],
  "electric-dirt-bikes-australia-buyers-guide-2026": ["electric bikes australia","how much are electric bikes","cheap electric dirt bikes","electric dirt bikes","electric bike australia","electric dirt bike","electric dirt bike australia"],
  "talaria-sting-review-australia": ["electric dirt bike","electric dirt bike australia","electric dirt bikes","electric bike australia"],
  "stark-varg-review-australia-2026": ["electric bike australia","electric dirt bike","electric dirt bike australia","electric dirt bikes"],
  "kids-electric-bike-buying-guide-australia": ["electric bikes australia","electric bike for kids","childrens electric bikes","small electric bike","ktm electric dirt bike","electric dirt bikes","electric bike australia","electric dirt bike"],
  "electric-pit-bike-australia-guide": ["electric bikes australia","how much are electric bikes","cheap electric dirt bikes","electric dirt bike australia","electric dirt bikes","electric bike australia","electric dirt bike"],
  "electric-fat-bike-guide-australia": ["electric bikes australia","electric bike australia","electric dirt bike","electric dirt bike australia","electric dirt bikes"],
  "off-road-electric-bike-australia-guide": ["electric bikes australia","electric off road bike","off road electric bikes","electric bike laws australia","electric bike laws qld","electric bike regulations nsw","nsw e bike certification laws","electric dirt bike"],
  "72v-battery-upgrade-guide-electric-dirt-bike": ["electric bikes australia","electric bike australia","electric dirt bike","electric dirt bike australia","electric dirt bikes"],
  "electric-enduro-bike-australia-review": ["electric bikes australia","electric trail bike","electric bike australia","electric dirt bike","electric dirt bike australia","electric dirt bikes"],
  "oset-bikes-australia-review-junior-electric": ["electric bikes australia","electric dirt bikes","electric bike australia","electric dirt bike","electric dirt bike australia"],
  "e-ride-pro-australia-review": ["electric bikes australia","electric dirt bikes","electric bike australia","electric dirt bike","electric dirt bike australia"],
  "electric-motor-bike-australia-guide-2026": ["electric motor bike","electric motor bikes","electric motorbikes","electric bike laws australia","electric bike laws qld","electric bike regulations nsw","nsw e bike certification laws","electric dirt bike"],
  "kids-electric-motorbike-australia-buyers-guide": ["electric motor bike","electric motor bikes","electric motorbikes","childs electric motorbike","electric motor bikes australia","electric child","how much are electric bikes","cheap electric dirt bikes"],
  "rtr-ebike-australia-review": ["australian e bikes","australian e-bike","electric bike laws australia","electric bike laws qld","electric bike regulations nsw","nsw e bike certification laws","electric dirt bike australia","electric dirt bikes"],
  "best-ebike-australia-2026": ["e bike off road","off road ebikes","childrens electric bikes","small electric bike","ktm electric dirt bike","electric bike australia","electric dirt bike","electric dirt bike australia"],
  "childs-electric-motorcycle-australia-complete-guide": ["electric motorcycle","australian electric motorcycle","electric child","childrens electric bikes","small electric bike","ktm electric dirt bike","e motorcycles","e motorbikes australia"],
  "road-legal-electric-motorcycle-australia-guide": ["electric motorcycle","australian electric motorcycle","electric motorcycle road legal","electric bike laws australia","electric bike laws qld","electric bike regulations nsw","nsw e bike certification laws","e-bike laws"],
  "electric-motorbike-vs-petrol-australia-2026": ["electric motor bike","electric motor bikes","electric motorbikes","electric motor bikes australia","electric bike australia","electric dirt bike","electric dirt bike australia","electric dirt bikes"],
  "best-electric-bike-australia-complete-guide": ["electric bikes australia","electric dirt bikes","electric bike australia","electric dirt bike","electric dirt bike australia"],
  "how-fast-do-electric-dirt-bikes-go": ["electric bikes australia","fast electric bikes","fastest ebike australia","fastest e bike australia","faster electric bike","electric bike australia","electric dirt bike","electric dirt bike australia"],
  "electric-dirt-bike-cost-australia-price-guide": ["electric bikes australia","how much are electric bikes","cheap electric dirt bikes","electric dirt bike australia","electric dirt bikes","electric bike australia","electric dirt bike"],
  "electric-dirt-bike-licence-requirements-australia": ["electric bikes australia","electric bike laws australia","electric bike laws qld","electric bike regulations nsw","nsw e bike certification laws","electric dirt bike australia","electric dirt bikes","electric bike australia"],
  "electric-dirt-bike-battery-lifespan-replacement-cost": ["electric bikes australia","electric dirt bike australia","electric dirt bikes","electric bike australia","electric dirt bike"],
  "electric-dirt-bike-finance-payment-plans-australia": ["electric bikes australia","how much are electric bikes","cheap electric dirt bikes","electric dirt bike australia","electric dirt bikes","electric bike australia","electric dirt bike"],
  "sur-ron-horsepower-power-specs-explained": ["fast electric bikes","fastest ebike australia","fastest e bike australia","faster electric bike","electric dirt bike australia","electric dirt bikes","electric bike australia","electric dirt bike"],
  "what-age-can-kids-ride-electric-dirt-bikes": ["electric bikes australia","childrens electric bikes","small electric bike","ktm electric dirt bike","electric bike australia","electric dirt bike","electric dirt bike australia","electric dirt bikes"],
  "electric-bike-registration-nsw-guide": ["electric bikes australia","electric bike laws australia","electric bike laws qld","electric bike regulations nsw","nsw e bike certification laws","electric dirt bike australia","electric dirt bikes","electric bike australia"],
  "rfn-ares-rally-pro-review-dual-ergonomics": ["electric dirt bike","electric dirt bike australia","electric dirt bikes","electric bike australia"],
  "segway-x260-vs-x160-electric-dirt-bike-comparison": ["electric bikes australia","electric bike australia","electric dirt bike","electric dirt bike australia","electric dirt bikes"],
  "electric-dirt-bike-servicing-cost-guide-australia": ["electric bikes australia","electric dirt bike","electric dirt bike australia","electric dirt bikes","electric bike australia"],
  "electric-dirt-bike-tyres-knobby-vs-trials-guide": ["electric bikes australia","electric dirt bike","electric dirt bike australia","electric dirt bikes","electric bike australia"],
  "electric-dirt-bike-insurance-australia-guide": ["electric bikes australia","electric bike laws australia","electric bike laws qld","electric bike regulations nsw","nsw e bike certification laws","electric dirt bikes","electric bike australia","electric dirt bike"],
  "best-electric-dirt-bike-lighting-kits-night-riding": ["electric bikes australia","electric dirt bikes","electric bike australia","electric dirt bike","electric dirt bike australia"],
  "rtr-ebike-vs-super-soco-cpx-commuter-comparison": ["australian e bikes","australian e-bike","electric dirt bike australia","electric dirt bikes","electric bike australia","electric dirt bike"],
  "electric-dirt-bike-road-legal-australia": ["electric bikes australia","electric bike laws australia","electric bike laws qld","electric bike regulations nsw","nsw e bike certification laws","electric dirt bike australia","electric dirt bikes","electric bike australia"],
  "best-electric-motorcycle-australia-2026": ["electric motorcycle","australian electric motorcycle","e motorcycles","e motorbikes australia","electric dirt bike","electric dirt bike australia","electric dirt bikes","electric bike australia"],
  "talaria-sting-battery-upgrade-guide": ["electric dirt bikes","electric bike australia","electric dirt bike","electric dirt bike australia"],
  "crypto-discount-electric-bike-australia": ["electric bikes australia","electric dirt bike","electric dirt bike australia","electric dirt bikes","electric bike australia"],
  "electric-dirt-bike-payid-australia": ["electric bikes australia","electric dirt bike","electric dirt bike australia","electric dirt bikes","electric bike australia"],
  "electric-bike-laws-qld-2026": ["electric bike laws qld","electric bike laws australia","new electric bike laws","new ebike laws","electric bikes australia","e-bikes for sale","electric bikes on sale","electric bikes for sale brisbane"],
  "electric-bike-regulations-nsw-2026": ["electric bike regulations nsw","e bike regulations nsw","nsw e bike certification laws","legal e bikes nsw","electric bikes nsw laws","new ebike laws nsw","electric bike laws australia","e bikes for sale sydney","e bike price in australia","electric bike for sale sydney"],
  "australian-electric-motorcycle-guide-2026": ["australian electric motorcycle","australia electric motorcycle","electric motorcycle australia","e motorcycles","electric motorbike australia","electric motorcycle for sale","electric motorbikes for sale","electric motorbike for sale"],
  "e-ride-pro-australia-buyers-guide": ["e ride pro","e ride pro australia","e ride bike","e-ride pro ss","electric dirt bike australia","electric dirt bike for sale","electric dirt bikes for sale","dirtbike sales"],
  "e-ride-pro-ss-2-0-vs-sr-specs-price": ["e-ride pro ss","e ride pro ss","e ride pro ss australia","eride pro ss australia","e ride pro","electric motorcycles for sale","dirtbike sale","electric dirt bike australia for sale"],
  "e-bike-safety-australia-guide": ["e bike safety australia","electric bike laws australia","electric bikes australia","e bike parts australia","electric bikes for sale melbourne","e bikes for sale melbourne"],
  "childs-dirt-bike-australia-electric-options": ["childs dirt bike","dirt bike for kids","electric dirt bike for kids","childrens electric dirt bike","kids electric dirt bike","affordable dirt bikes for sale","dirt cheap dirt bikes for sale","cheap dirt bikes for sale under $1000"],
  "adult-electric-dirt-bike-australia-best-models": ["adult electric dirt bike","electric dirt bike adults","electric dirt bike for adults","electric motorbike for adults","adult electric bike","electric motor bikes for sale","electric bikes for sale perth","e bikes for sale perth"],
  "high-performance-electric-dirt-bike-australia": ["high performance electric dirt bike","electric motor cross bikes","electric motocross bike","electric dirt bike","best electric dirt bike","dirt motorcycles for sale","motorcycle dirt bike for sale","dirt bike motorcycles for sale"],
  "125cc-dirt-bike-australia-electric-alternatives": ["125cc dirt bike","250cc dirt bikes","150cc dirt bike","dirt bike 125cc","125cc dirtbike","250 dirt bike","electric dirt bike","250 dirt bike for sale","road registered dirt bikes","motorcycle dirt bikes for sale"],
  "kids-ebike-australia-evo-racing-lil-rippa-compared": ["kids ebike","childs electric bike","electric bike kids","childs e bike","electric kids bike","kids e bike","mini bike dirt bike","cheap electric bikes for sale","electric bike for sale melbourne"],
  "electric-moped-vs-e-scooter-australia-lams-guide": ["moped e scooter","electric motorcycles and scooters","electric motorcycle scooter","electric moped","electric motorcycle moped","moped prices","road registered electric bike","electric road bikes for sale"],
};

export function blogTags(slug: string): string[] {
  return BLOG_TAGS[slug] ?? [];
}
